sonar.projectKey=sonarqube-java-demo
sonar.projectName=SonarQube Java Demo
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.binaries=target/classes
sonar.host.url=http://34.69.176.101:9000/
sonar.token=sqa_3601cd2b17b2308d6746c03ae07f861202e721f9


# Note: sonar.host.url and sonar.token are passed via GitHub Secrets

